# Generated by Django 4.2.4 on 2023-08-03 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 3, 21, 5, 23, 38867))),
                ('invoiceNo', models.IntegerField()),
                ('customerName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='invoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=4, max_digits=7)),
                ('price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('invoicee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
            ],
            options={
                'verbose_name': 'invoiceDetail',
                'verbose_name_plural': 'invoiceDetail',
            },
        ),
    ]
