# Generated by Django 4.2.4 on 2023-08-03 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 21, 12, 42, 356004)),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='unitPrice',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
